{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9a4e5b80-509a-4784-8389-46b2e7c88804",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-01-11 18:18:41.391 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "\n",
    "import re\n",
    "\n",
    "st.set_page_config(page_title=\"Table Extractor\", layout=\"centered\")\n",
    "\n",
    "st.title(\"📄 استخراج أسماء الجداول\")\n",
    "\n",
    "st.write(\"ارفع ملف نصي (TXT) وسيتم عرض أسماء الجداول الموجودة فيه\")\n",
    "\n",
    "# ============================\n",
    "\n",
    "# رفع الملف\n",
    "\n",
    "# ============================\n",
    "\n",
    "uploaded_file = st.file_uploader(\"📤 اختر ملف txt\", type=[\"txt\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    text = uploaded_file.read().decode(\"utf-8\")\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # إزالة التعليقات\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    text_clean = re.sub(r'--.*', '', text)\n",
    "\n",
    "    text_clean = re.sub(r'/\\*.*?\\*/', '', text_clean, flags=re.DOTALL)\n",
    "\n",
    "    tables = []\n",
    "\n",
    "    # تنظيف اسم الجدول\n",
    "\n",
    "    def clean_table_name(name):\n",
    "\n",
    "        name = name.split()[0]                 # إزالة alias\n",
    "\n",
    "        name = re.split(r'[#\"(\\}]', name)[0]   # إيقاف عند الرموز\n",
    "\n",
    "        return name.strip()\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # FROM\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    from_pattern = r'\\bFROM\\s+([^\\s;]+(?:\\s*,\\s*[^\\s;]+)*)'\n",
    "\n",
    "    from_matches = re.findall(from_pattern, text_clean, re.IGNORECASE)\n",
    "\n",
    "    for part in from_matches:\n",
    "\n",
    "        for t in part.split(','):\n",
    "\n",
    "            t = t.strip()\n",
    "\n",
    "            if t and not t.startswith('('):\n",
    "\n",
    "                tables.append(clean_table_name(t))\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # JOIN\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    join_pattern = r'\\bJOIN\\s+([^\\s\\(\\);]+)'\n",
    "\n",
    "    join_matches = re.findall(join_pattern, text_clean, re.IGNORECASE)\n",
    "\n",
    "    for t in join_matches:\n",
    "\n",
    "        if not t.startswith('('):\n",
    "\n",
    "            tables.append(clean_table_name(t))\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # إزالة التكرار\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    tables_unique = list(dict.fromkeys(tables))\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # عرض النتائج\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    st.success(f\"✅ تم استخراج {len(tables_unique)} جدول\")\n",
    "\n",
    "    st.subheader(\"📋 أسماء الجداول\")\n",
    "\n",
    "    for table in tables_unique:\n",
    "\n",
    "        st.write(table)\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b673392-771f-4688-9d93-2ab79ec10838",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
