{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "074589a4-b894-44ab-9371-ca4eb0bad63f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-07 19:50:52.845 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "\n",
    "import re\n",
    "\n",
    "st.set_page_config(page_title=\"SQL Tables Extractor\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📊 استخراج وتصنيف الجداول من SQL / Power Query\")\n",
    "\n",
    "st.write(\"ارفع ملف النص (TXT) وسيتم استخراج الجداول وتصنيفها مع إمكانية التحميل.\")\n",
    "\n",
    "# ============================\n",
    "\n",
    "# رفع الملف\n",
    "\n",
    "# ============================\n",
    "\n",
    "uploaded_file = st.file_uploader(\"📂 ارفع ملف TXT\", type=[\"txt\"])\n",
    "\n",
    "def clean_table_name(name):\n",
    "\n",
    "    return name.strip('()[]{}\"').strip()\n",
    "\n",
    "if uploaded_file:\n",
    "\n",
    "    sql_text = uploaded_file.read().decode(\"utf-8\")\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # تنظيف التعليقات\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    sql_text_clean = re.sub(r'--.*', '', sql_text)\n",
    "\n",
    "    sql_text_clean = re.sub(r'/\\*.*?\\*/', '', sql_text_clean, flags=re.DOTALL)\n",
    "\n",
    "    tables = []\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # FROM\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    from_pattern = r'\\bFROM\\s+([^\\s;]+(?:\\s*,\\s*[^\\s;]+)*)'\n",
    "\n",
    "    for from_part in re.findall(from_pattern, sql_text_clean, re.IGNORECASE):\n",
    "\n",
    "        for t in from_part.split(','):\n",
    "\n",
    "            table_name = t.split('#(lf)')[0].strip()\n",
    "\n",
    "            if table_name and not table_name.startswith('('):\n",
    "\n",
    "                table_name_clean = clean_table_name(table_name.split()[0])\n",
    "\n",
    "                if table_name_clean:\n",
    "\n",
    "                    tables.append(table_name_clean)\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # JOIN\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    join_pattern = r'\\bJOIN\\s+([^\\s\\(\\);]+)'\n",
    "\n",
    "    for t in re.findall(join_pattern, sql_text_clean, re.IGNORECASE):\n",
    "\n",
    "        table_name = t.split('#(lf)')[0].strip()\n",
    "\n",
    "        if table_name and not table_name.startswith('('):\n",
    "\n",
    "            table_name_clean = clean_table_name(table_name.split()[0])\n",
    "\n",
    "            if table_name_clean:\n",
    "\n",
    "                tables.append(table_name_clean)\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # Views من Power Query\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    view_pattern = r'Name\\s*=\\s*\"([^\"]+)\"'\n",
    "\n",
    "    for match in re.findall(view_pattern, sql_text_clean):\n",
    "\n",
    "        view_name_clean = clean_table_name(match)\n",
    "\n",
    "        if view_name_clean and view_name_clean not in tables:\n",
    "\n",
    "            tables.append(view_name_clean)\n",
    "\n",
    "    # إزالة التكرار\n",
    "\n",
    "    tables_unique = list(dict.fromkeys(tables))\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # التصنيف\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    admin_tables = []\n",
    "\n",
    "    dp_tables = []\n",
    "\n",
    "    no_schema_tables = []\n",
    "\n",
    "    for table in tables_unique:\n",
    "\n",
    "        if '.' in table:\n",
    "\n",
    "            schema_part = table.split('.')[0].lower()\n",
    "\n",
    "            if 'omi' in schema_part:\n",
    "\n",
    "                admin_tables.append(table)\n",
    "\n",
    "            else:\n",
    "\n",
    "                dp_tables.append(table)\n",
    "\n",
    "        else:\n",
    "\n",
    "            no_schema_tables.append(table)\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # العرض\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    st.success(f\"✅ عدد الجداول الكلي: {len(tables_unique)}\")\n",
    "\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "\n",
    "    with col1:\n",
    "\n",
    "        st.subheader(\"📝 جداول الإدارة\")\n",
    "\n",
    "        if admin_tables:\n",
    "\n",
    "            st.write(admin_tables)\n",
    "\n",
    "        else:\n",
    "\n",
    "            st.write(\"لا يوجد\")\n",
    "\n",
    "    with col2:\n",
    "\n",
    "        st.subheader(\"📝 جداول المستودعات التقنية\")\n",
    "\n",
    "        if dp_tables:\n",
    "\n",
    "            st.write(dp_tables)\n",
    "\n",
    "        else:\n",
    "\n",
    "            st.write(\"لا يوجد\")\n",
    "\n",
    "    with col3:\n",
    "\n",
    "        st.subheader(\"📝 بدون سكيما\")\n",
    "\n",
    "        if no_schema_tables:\n",
    "\n",
    "            st.write(no_schema_tables)\n",
    "\n",
    "        else:\n",
    "\n",
    "            st.write(\"لا يوجد\")\n",
    "\n",
    "    st.subheader(\"📋 جميع الجداول\")\n",
    "\n",
    "    st.write(tables_unique)\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    # تجهيز ملف التحميل\n",
    "\n",
    "    # ============================\n",
    "\n",
    "    output_text = \"\"\n",
    "\n",
    "    output_text += f\"عدد الجداول الكلي: {len(tables_unique)}\\n\\n\"\n",
    "\n",
    "    output_text += \"جداول الإدارة:\\n\"\n",
    "\n",
    "    for t in admin_tables:\n",
    "\n",
    "        output_text += f\"- {t}\\n\"\n",
    "\n",
    "    output_text += \"\\nجداول المستودعات التقنية:\\n\"\n",
    "\n",
    "    for t in dp_tables:\n",
    "\n",
    "        output_text += f\"- {t}\\n\"\n",
    "\n",
    "    output_text += \"\\nجداول بدون سكيما:\\n\"\n",
    "\n",
    "    for t in no_schema_tables:\n",
    "\n",
    "        output_text += f\"- {t}\\n\"\n",
    "\n",
    "    output_text += \"\\nجميع الجداول:\\n\"\n",
    "\n",
    "    for t in tables_unique:\n",
    "\n",
    "        output_text += f\"- {t}\\n\"\n",
    "\n",
    "    st.download_button(\n",
    "\n",
    "        label=\"⬇️ تحميل النتائج TXT\",\n",
    "\n",
    "        data=output_text,\n",
    "\n",
    "        file_name=\"tables_list.txt\",\n",
    "\n",
    "        mime=\"text/plain\"\n",
    "\n",
    "    )\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ad23399-f22d-442a-83a7-3652e35911a7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
