{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bb7ea6d1-cdaa-4596-96bb-d00c2be84782",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import re\n",
    "# إعداد الصفحة\n",
    "st.set_page_config(page_title=\"Table Extractor with Schema\", layout=\"centered\")\n",
    "st.title(\"📄 استخراج أسماء الجداول وتصنيفها حسب السكيما\")\n",
    "st.write(\"ارفع ملف نصي (TXT) وسيتم عرض أسماء الجداول الموجودة فيه وتصنيفها حسب السكيما.\")\n",
    "# ============================\n",
    "# رفع الملف\n",
    "# ============================\n",
    "uploaded_file = st.file_uploader(\"📤 اختر ملف txt\", type=[\"txt\"])\n",
    "if uploaded_file is not None:\n",
    "   # قراءة محتوى الملف\n",
    "   sql_text = uploaded_file.read().decode(\"utf-8\")\n",
    "   # تنظيف التعليقات\n",
    "   sql_text_clean = re.sub(r'--.*', '', sql_text)\n",
    "   sql_text_clean = re.sub(r'/\\*.*?\\*/', '', sql_text_clean, flags=re.DOTALL)\n",
    "   # دالة لتنظيف أسماء الجداول/Views\n",
    "   def clean_table_name(name):\n",
    "       return name.strip('()[]{}\"').strip()\n",
    "   tables = []\n",
    "   # استخراج FROM\n",
    "   from_pattern = r'\\bFROM\\s+([^\\s;]+(?:\\s*,\\s*[^\\s;]+)*)'\n",
    "   for from_part in re.findall(from_pattern, sql_text_clean, re.IGNORECASE):\n",
    "       for t in from_part.split(','):\n",
    "           table_name = t.split('#(lf)')[0].strip()\n",
    "           if table_name and not table_name.startswith('('):\n",
    "               table_name_clean = clean_table_name(table_name.split()[0])\n",
    "               if table_name_clean:\n",
    "                   tables.append(table_name_clean)\n",
    "   # استخراج JOIN\n",
    "   join_pattern = r'\\bJOIN\\s+([^\\s\\(\\);]+)'\n",
    "   for t in re.findall(join_pattern, sql_text_clean, re.IGNORECASE):\n",
    "       table_name = t.split('#(lf)')[0].strip()\n",
    "       if table_name and not table_name.startswith('('):\n",
    "           table_name_clean = clean_table_name(table_name.split()[0])\n",
    "           if table_name_clean:\n",
    "               tables.append(table_name_clean)\n",
    "   # استخراج أسماء الـ Views من Power Query\n",
    "   view_pattern = r'Name\\s*=\\s*\"([^\"]+)\"'\n",
    "   for match in re.findall(view_pattern, sql_text_clean):\n",
    "       view_name_clean = clean_table_name(match)\n",
    "       if view_name_clean and view_name_clean not in tables:\n",
    "           tables.append(view_name_clean)\n",
    "   # إزالة التكرار\n",
    "   tables_unique = list(dict.fromkeys(tables))\n",
    "   # ============================\n",
    "   # ١. طباعة عدد الجداول الكلي\n",
    "   # ============================\n",
    "   st.success(f\"✅ عدد الجداول الكلي: {len(tables_unique)}\")\n",
    "   # ============================\n",
    "   # ٢. طباعة قائمة جميع الجداول قبل التصنيف\n",
    "   # ============================\n",
    "   st.subheader(\"📋 جميع الجداول بشكل عام:\")\n",
    "   for i, table in enumerate(tables_unique, 1):\n",
    "       st.write(f\"{i}. {table}\")\n",
    "   st.write(\"---\")\n",
    "   # ============================\n",
    "   # ٣. تصنيف الجداول حسب السكيما\n",
    "   # ============================\n",
    "   admin_tables = []        # جداول الإدارة\n",
    "   dp_tables = []           # جداول المستودعات التقنية\n",
    "   no_schema_tables = []    # لا يوجد سكيما\n",
    "   for table in tables_unique:\n",
    "       if '.' in table:\n",
    "           schema_part = table.split('.')[0].lower()\n",
    "           if 'omi' in schema_part:\n",
    "               admin_tables.append(table)      # أي شيء يحتوي omi → إدارة\n",
    "           else:\n",
    "               dp_tables.append(table)         # أي سكيما أخرى مع نقطة → المستودعات التقنية\n",
    "       else:\n",
    "           no_schema_tables.append(table)     # بدون نقطة → لا يوجد سكيما\n",
    "   # طباعة النتائج حسب القسم\n",
    "   st.subheader(\"📝 جداول الإدارة:\")\n",
    "   if admin_tables:\n",
    "       for i, table in enumerate(admin_tables, 1):\n",
    "           st.write(f\"{i}. {table}\")\n",
    "   else:\n",
    "       st.write(\"لا يوجد جداول للإدارة.\")\n",
    "   st.subheader(\"📝 جداول المستودعات التقنية:\")\n",
    "   if dp_tables:\n",
    "       for i, table in enumerate(dp_tables, 1):\n",
    "           st.write(f\"{i}. {table}\")\n",
    "   else:\n",
    "       st.write(\"لا يوجد جداول للمستودعات التقنية.\")\n",
    "   st.subheader(\"📝 لا يوجد سكيما للجداول الأخرى:\")\n",
    "   if no_schema_tables:\n",
    "       for i, table in enumerate(no_schema_tables, 1):\n",
    "           st.write(f\"{i}. {table}\")\n",
    "   else:\n",
    "       st.write(\"لا يوجد جداول بدون سكيما.\")\n",
    "   # ============================\n",
    "   # تحميل النتائج كملف txt\n",
    "   # ============================\n",
    "   st.download_button(\n",
    "       label=\"⬇️ تحميل جميع الجداول\",\n",
    "       data=\"\\n\".join(tables_unique),\n",
    "       file_name=\"tables_list_with_schema.txt\",\n",
    "       mime=\"text/plain\"\n",
    "   )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
